services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    volumes:
      - /tmp:/tmp
    environment:
      - MAX_CONTENT_LENGTH=52428800

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    restart: always
